### ISSUE TITLE
New controls package to specify motion directly

### ISSUE THREAD

**Issue by VasilyF** [mcgill-robotics/AUV-2020#44]
### What's wrong with the current controls package?

It operates by attempting to bring the AUV into a particular state. The planner would use this controller if it only cares that the AUV ends up in a particular position/orientation - it doesn't stipulate anything about the path/intermediate states the AUV goes through to get there. However, there are situations when we would want control over *how the AUV moves* rather than *how it ends up*. 

- Going through the gate 'with style': We might want the AUV to go straight while rolling/yawing. It's unwieldy to program this as a series of states because the states aren't what we care about, we care about the actual motion the AUV performs.
- Navigate using pinger: We wouldn't know *where* the pinger is; only it's bearing relative to the AUV. It's clunky to program going to the pinger source as a series of states because we don't know the position of the intended state (updating this in real time is clunky and would lead to jerky motion - the AUV slows down as it approaches some arbitrary setpoint only to speed up again because the pinger is still further away). It's more fitting that the planner issue a command like 'go in that direction'.
- For the current pool tests, we only care to test the AUV performs the correct motion and having to describe this using states is using a sledgehammer to drive in a nail.

### The proposal

Have several 'controls' packages that the planner can switch between using depending on what makes the most sense with what it's trying to accomplish (names tentative). 

- `state_controller` - specify a state(position/orientation) we want the AUV to assume.
- `local_motion_controller` - directly specify the motion you want the AUV to perform relative to the AUV's own reference frame
- `global_motion_controller` - directly specify the motion you want the AUV to perform relative to the world reference frame

To understand the difference between `local_motion_controller` and `global_motion_controller` consider what the AUV would do if issued the command to surge and yaw simultaneously:

   1. Go in a circle (former)
   2. Go in a straight line while spinning in place (latter)

### To do

Create a `local_motion_controller` package. Commands from planner are submitted to an action server within this package so that the planner can receive feedback or cancel the command. The motion command itself (action goal) should specify the following:

- surge [force - N]
- sway 
- heave 
- roll [torque - N*m]
- pitch
- yaw 
- duration [time - s]

Use whatever message format is appropriate, it's encouraged to use existing ros message types where applicable. 

The package should publish a `geometry_msgs/Wrench` message onto `/effort` - same as the current controls package.

**Comment by ben-jamming** [comment]
TODO: fix issue with roslaunch. 
`ERROR: cannot launch node of type [deadreackon_controls/src/superimposer.py]: deadreackon_controls/src`
